[options]
admin_passwd = $pbkdf2-sha512$600000$vtd67x1DCOFcyzmnNOb83w$IJGGBFqbpHuOeGl0UtcDF61Unx20NHpLGBlZ7g5aZHV9d142IZBszvnGtfb4IPWfqYRX3Gj1Trxajclh8rXAJA
db_host = db
db_port = 5432
db_user = odoo_dbuser
db_password = dbuser123
db_name = odoo18
addons_path = /mnt/odoo-src/addons,/mnt/custom-addons
list_db = True