# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import account_bank_statement
from . import account_cash_rounding
from . import account_fiscal_position
from . import account_fiscal_position_tax
from . import account_journal
from . import account_move
from . import account_payment
from . import account_tax
from . import account_tax_group
from . import barcode_rule
from . import binary
from . import decimal_precision
from . import digest
from . import ir_binary
from . import ir_http
from . import ir_module_module
from . import ir_ui_view
from . import mail_compose_message
from . import pos_bill
from . import pos_bus_mixin
from . import pos_category
from . import pos_config
from . import pos_load_mixin
from . import pos_note
from . import pos_order
from . import pos_payment
from . import pos_payment_method
from . import pos_printer
from . import pos_session
from . import product
from . import product_combo
from . import product_combo_item
from . import product_tag
from . import report_sale_details
from . import res_company
from . import res_config_settings
from . import res_country
from . import res_country_state
from . import res_currency
from . import res_lang
from . import res_partner
from . import res_users
from . import stock_picking
from . import stock_rule
from . import stock_warehouse
